export const LIST_HOTEL = [
    {
        id: 1,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: true,
    },
    {
        id: 2,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: true,
    },
    {
        id: 3,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: true,
    },
    {
        id: 4,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: false,
    },
    {
        id: 5,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: false,
    },
    {
        id: 6,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: false,
    },
    {
        id: 7,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: false,
    },
    {
        id: 8,
        name: 'Hotel 1',
        address: 'Address 1, City 1, Country 1, Zip 1',
        pricePerNight: 100,
        rating: 3.4,
        reviewCount: 100,
        score: {
            overAll: 4.1,
            houseKeeping: 3,
            food: 4,
            service: 4,
            staff: 3,
        },
        serviceType: [1, 2, 3, 4, 5, 6],
        image: 'https://source.unsplash.com/random',
        previewImage: [
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
            'https://source.unsplash.com/random',
        ],
        rooms: [
            {
                type: 1,
                name: 'Room 1',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 2,
                name: 'Room 2',
                price: 100,
                image: 'https://source.unsplash.com/random',
            },
            {
                type: 3,
                name: 'Room 3',
                price: 100,
                image: 'https://source.unsplash.com/random',
            }
        ],
        description: 'Description 1',
        isRecentSearch: false,
    },
]

export const LIST_RECOMAND = [
    {
        id: 1,
        title: 'Trips to Thailand',
        description: 'Get 30% off on flight booking.',
        image: 'https://source.unsplash.com/random',
    },
    {
        id: 2,
        title: 'Trips to Thailand',
        description: 'Get 30% off on flight booking.',
        image: 'https://source.unsplash.com/random',
    },
    {
        id: 3,
        title: 'Trips to Thailand',
        description: 'Get 30% off on flight booking.',
        image: 'https://source.unsplash.com/random',
    },
    {
        id: 4,
        title: 'Trips to Thailand',
        description: 'Get 30% off on flight booking.',
        image: 'https://source.unsplash.com/random',
    },
]